baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Upobir's Blog"
theme = "gokarna"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "posts"
    url = "/posts/"
    name = "Posts"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/upobir/"
    weight = 3
    pre = "<span data-feather='github'></span>"

[params]
  avatarURL = "https://scontent-ams4-1.xx.fbcdn.net/v/t39.30808-6/279820946_4956690371094559_3756523257406412059_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=9c7eae&_nc_eui2=AeHYxHlL-W0vQVZ9eIF8DFW1qka4ROoHW16qRrhE6gdbXnsCRYPTyUv-b0oC9vVKT207RHY5BtFG4BW-Gy4WAvSW&_nc_ohc=di2GSpiE7i8AX-dqp-y&_nc_ht=scontent-ams4-1.xx&oh=00_AfD24n9WCidypK4FTQfKgo_TkrVQ-KuZp_-RWwv90XztCw&oe=65C2D070"
  avatarSize = "size-l"
  description = "I love mathematics and programming!"
  accentColor = "#FF4D4D"
  ShowBackToTopButton = true
  customHeadHTML = '''
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css" integrity="sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV" crossorigin="anonymous">
  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js" integrity="sha384-XjKyOOlGwcjNTAIQHIpgOno0Hl1YQqzUOEleOLALmuqehneUG+vnGctmUb0ZY0l8" crossorigin="anonymous"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js" integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05" crossorigin="anonymous"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          delimiters: [
              {left: '$$', right: '$$', display: true},
              {left: '$', right: '$', display: false},
          ],
          throwOnError : false
        });
    });
  </script>
  '''
  showPostsOnHomePage = "popular"


  metaKeywords = ["blog", "upobir", "sabbir rahman"]
  footer = "Sabbir Rahman"

  socialIcons = [
    {name = "twitter", url = "https://twitter.com/upobir"},
    {name = "linkedin", url = "https://www.linkedin.com/in/upobir/"},
    {name = "facebook", url = "https://www.facebook.com/sabbir.r.abir/"},
    {name = "github", url = "https://github.com/upobir"},
  ]