name: Test on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run shell script
        run: |
          echo "::group::title 1"
          chmod +x ./ci-test.sh
          echo "::endgroup::"
          echo "::group::title 2"
          ./ci-test.sh
          echo "::endgroup::"